"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Target, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { EvidencePanel, type SelectedEvidence } from "@/components/evidence/evidence-panel";
import { StatusSelect } from "@/components/applications/status-select";
import { Toast } from "@/components/ui/toast";
import { cn, formatDate } from "@/lib/utils";
import type { getApplication } from "@/lib/db/queries";

type ApplicationDetail = NonNullable<Awaited<ReturnType<typeof getApplication>>>;

const findingTone = {
  strength: "border-emerald-200 bg-emerald-50 text-emerald-800",
  gap: "border-rose-200 bg-rose-50 text-rose-800",
  suggestion: "border-amber-200 bg-amber-50 text-amber-800",
  interview_prep: "border-indigo-200 bg-indigo-50 text-indigo-800",
};

export function ApplicationDetailClient({ application }: { application: ApplicationDetail }) {
  const [selectedEvidence, setSelectedEvidence] = React.useState<SelectedEvidence>(null);
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [showGenerationToast, setShowGenerationToast] = React.useState(false);
  const report = application.report;

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setShowGenerationToast(true);
    }, 1200);
  };

  return (
    <main className="min-h-screen bg-stone-50 px-6 py-6 max-sm:px-4">
      <div className="mx-auto grid max-w-7xl grid-cols-[minmax(0,1fr)_420px] gap-6 max-lg:grid-cols-1">
        <section>
          <Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-zinc-600 hover:text-zinc-950">
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            Dashboard
          </Link>

          <div className="mt-6 rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
            <div className="flex items-start justify-between gap-4 max-sm:flex-col">
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <StatusSelect applicationId={application.id} initialStatus={application.status} />
                  <Badge tone={application.priority}>{application.priority} priority</Badge>
                </div>
                <h1 className="mt-4 text-3xl font-semibold tracking-normal text-zinc-950">{application.job.title}</h1>
                <p className="mt-2 text-zinc-600">{application.job.company} · {application.job.location}</p>
              </div>

              {report ? (
                <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-5 py-4 text-center">
                  <p className="text-sm font-medium text-indigo-700">Fit score</p>
                  <p className="mt-1 text-4xl font-semibold text-indigo-950">{report.fitScore}%</p>
                </div>
              ) : (
                <div className="rounded-lg border border-zinc-200 bg-zinc-50 px-5 py-4 text-center">
                  <p className="text-sm font-medium text-zinc-550">Fit score</p>
                  <p className="mt-1 text-4xl font-semibold text-zinc-400">-%</p>
                </div>
              )}
            </div>
            <p className="mt-6 max-w-3xl text-base leading-7 text-zinc-700">
              {report
                ? report.summary
                : "No AI analysis has been generated for this application yet. Generate a fit report to automatically analyze strengths, key skill gaps, recommendations, and sample interview questions backed by exact source line citations."}
            </p>
            <div className="mt-5 flex flex-wrap gap-3 text-sm text-zinc-600">
              <span>Deadline: {formatDate(application.deadline)}</span>
              {report && (
                <>
                  <span>Generated by: {report.generatedBy}</span>
                  <span>Prompt: {report.promptVersion}</span>
                </>
              )}
            </div>
          </div>

          {report ? (
            <div className="mt-6 space-y-4">
              {report.findings
                .slice()
                .sort((a, b) => a.displayOrder - b.displayOrder)
                .map((finding) => (
                  <article key={finding.id} className="rounded-lg border border-zinc-200 bg-white p-5 shadow-sm">
                    <div className="flex flex-wrap items-center gap-3">
                      <span className={cn("rounded-md border px-2 py-1 text-xs font-semibold", findingTone[finding.type])}>
                        {finding.type.replace("_", " ")}
                      </span>
                      <Badge tone={finding.severity}>{finding.severity}</Badge>
                    </div>
                    <h2 className="mt-4 text-xl font-semibold text-zinc-950">{finding.title}</h2>
                    <p className="mt-3 leading-7 text-zinc-700">{finding.explanation}</p>
                    <div className="mt-4 rounded-md bg-zinc-50 p-4">
                      <p className="text-sm font-semibold text-zinc-900">Recommendation</p>
                      <p className="mt-2 text-sm leading-6 text-zinc-700">{finding.recommendation}</p>
                    </div>
                    <div className="mt-4 flex flex-wrap gap-2">
                      {finding.citations.map((citation) => (
                        <button
                          key={citation.id}
                          type="button"
                          onClick={() => setSelectedEvidence({ sourceType: citation.sourceType, sourceId: citation.sourceId })}
                          className="inline-flex items-center gap-2 rounded-md border border-zinc-200 bg-white px-3 py-2 text-sm font-medium text-zinc-700 transition hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-900"
                        >
                          <Target className="h-4 w-4" aria-hidden="true" />
                          {citation.sourceType === "resume_line" ? "Resume" : "Job"} lines {citation.startLine}-{citation.endLine}
                        </button>
                      ))}
                    </div>
                  </article>
                ))}
            </div>
          ) : (
            <div className="mt-6 rounded-lg border border-zinc-200 bg-white p-8 text-center shadow-sm">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-indigo-50 text-indigo-650">
                <Sparkles className="h-6 w-6" aria-hidden="true" />
              </div>
              <h3 className="mt-4 text-lg font-semibold text-zinc-950">No AI Report Available</h3>
              <p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-zinc-600">
                Analyze this application to extract strengths, identify skill gaps, and get structured interview prep questions with line-level evidence.
              </p>
              <button
                type="button"
                disabled={isGenerating}
                onClick={handleGenerateReport}
                className="mt-6 inline-flex items-center gap-2 rounded-md bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white shadow-xs transition hover:bg-indigo-850 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
              >
                {isGenerating ? (
                  <>
                    <svg className="h-4 w-4 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                    <span>Analyzing application...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" aria-hidden="true" />
                    <span>Generate AI Report</span>
                  </>
                )}
              </button>
            </div>
          )}

          <div className="mt-6 rounded-lg border border-zinc-200 bg-white p-5 shadow-sm">
            <h2 className="text-lg font-semibold text-zinc-950">Job description</h2>
            <p className="mt-3 leading-7 text-zinc-700">{application.job.description}</p>
            <a
              href={application.job.jobUrl}
              className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-indigo-700 hover:text-indigo-900"
            >
              Source listing <ExternalLink className="h-4 w-4" aria-hidden="true" />
            </a>
          </div>
        </section>

        <EvidencePanel
          resumeLines={application.resumeLines}
          jobRequirements={application.job.requirements}
          selected={selectedEvidence}
        />
      </div>

      {showGenerationToast && (
        <Toast
          message="Real AI report generation is disabled for this v1 portfolio demo. OpenAI API structured output analysis is scheduled for Phase 2."
          type="error"
          onClose={() => setShowGenerationToast(false)}
        />
      )}
    </main>
  );
}
